version: "3.7"
services:
  app:
    build:
      args:
        user: sterling
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: billkill
    container_name: billkill-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - billkill

  db:
    image: mysql:5.7
    container_name: billkill-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - billkill
    ports:
      - "4306:3306"

  nginx:
    image: nginx:alpine
    container_name: billkill-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - billkill

  vue:
    container_name: billkill-vue
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app:cached
    networks:
      - billkill
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "80"
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  billkill:
    driver: bridge
